version: '2'

services:

  oereb-print:
    networks:
    - print-network
    image: jura_oereb_print:latest
    environment:
      PRINT_YAML_MAX_ALIASES: 200
      LOG_LEVEL: INFO
      CATALINA_OPTS: >-
        -Xmx512M
        -Dmapfish.maxContentLength=4194304
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro
    ports:
      - 8680:8080

networks:
  print-network:
    external: true
